spring:
  application:
    name: hwSeminarEightSite                                                                                                                                                       
  main:
    banner-mode: "off"
external:
  services:
    gatewayUri: http://localhost:8765
    storeBasicAuth: "user:password"