spring:
  application:
    name: hwSeminarEightSite                                                                                                                                                       
  main:
    banner-mode: "off"
external:
  services:
    storeUri: http://localhost:8765/store
    paymentUri: http://localhost:8765/payment