spring:
  application:
    name: hwSeminarEightSite                                                                                                                                                       
  main:
    banner-mode: "off"
external:
  services:
    storeUri: http://localhost:8081
    paymentUri: http://localhost:8082